version: 2
jobs:
  ui:
    working_directory: ~/portfolio/portfolio-core-ui
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - restore_cache:
          key: v1-cypress-cache-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.cache/Cypress
      - run:
          name: Install local dependencies
          command: npm install --force --legacy-peer-deps --verbose
      - run:
          name: Install Cypress
          command: npm install cypress
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-cypress-cache-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.cache/Cypress

      # Lint the source code
      # - run:
      #     name: Linting
      #     command: npm run lint
      # Test the source code
      # - run:
      #     name: Testing
      #     command: npm run test
      # End to End test
      - run:
          name: End to End Test
          command: npm run e2e
      - run:
          name: Code Coverage Upload
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov 
            chmod +x codecov
            ./codecov -t ${{ secrets.CODECOV_UI_TOKEN }}


  backend:
    working_directory: ~/portfolio/upgraded-disco
    docker:
      - image: golang:1.19.5-bullseye
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
            - lint-dependencies
            - test-dependencies
      - run:
          name: Install Go Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install Lint Dependencies
          command: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.0
      - save_cache:
          key: lint-dependencies
          paths:
            - "/go/bin/golangci-lint"
      - run:
          name: Install Test Dependencies
          command: go install gotest.tools/gotestsum@latest
      - save_cache:
          key: test-dependencies
          paths:
            - "/go/bin/gotestsum"
      - run:
          name: Run Lint and Tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
            golangci-lint run --out-format=checkstyle > /tmp/test-reports/lint.xml
            cd /tmp/test-reports
            cat unit-tests.xml
            cat lint.xml
            curl -Os https://uploader.codecov.io/latest/linux/codecov 
            chmod +x codecov 
            ./codecov -t ${{ secrets.CODECOV_BACKEND_TOKEN }}
      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  build:
    jobs:
      - ui:
          context:
            - portfolio-projects
          filters:
            branches:
              only:
                - main
                - dev
      - backend:
          context:
            - portfolio-projects
          filters:
            branches:
              only:
                - main
                - dev
