version: "3.8"
services:
  go-dev:
    container_name: go-dev
    build:
      context: ./upgraded-disco
      dockerfile: Dockerfile
    volumes:
      - ./upgraded-disco:/app
      - ./tmp-vars.sh:/app/tmp-vars.sh
#      - /app/vendor
    networks:
      - common
    ports:
      - "8085:8085"
    command: ["/bin/bash", "-c", "source /app/tmp-vars.sh && air"]
    restart: always
    
  angular-dev:
    build:
      context: ./portfolio-core-ui
      dockerfile: Dockerfile
    volumes:
      - ./portfolio-core-ui:/app
      - /app/node_modules
    networks:
      - common
    ports:
      - "4200:4200"
    command: npm run start -- --host 0.0.0.0
    restart: always

networks:
  common:
    name: common
